version: "3"

services:
  nuxt:
    build: ./app/
    container_name: send-web
    restart: always
    ports:
      - "3000:3000"
    command:
      "npm run start"

  nginx:
    image: nginx:latest
    container_name: send-server
    ports:
      - "80:80"
    volumes:
      - ./nginx:/etc/nginx/conf.d
    depends_on:
      - nuxt
