version: '3'

services:
  nuxt:
    image: jamesacklin/send_nuxt:2.1.0
    container_name: send-web
    restart: always
    ports:
      - "3000:3000"
    command:
      "npm run start"
  nginx:
    image: nginx:1.13
    container_name: send-server
    ports:
      - "80:80"
    volumes:
      - ./server:/etc/nginx/conf.d
    depends_on:
      - nuxt
