version: '3'

services:
  nuxt:
    container_name: send-web
    build: ./app/
    restart: always
    ports:
      - "3000:3000"
    command:
      "npm run start"
  nginx:
    image: nginx:1.13
    container_name: send-server
    ports:
      - "80:80"
    volumes:
      - ./server:/etc/nginx/conf.d
    depends_on:
      - nuxt